// <auto-generated />
using MVCFirstApp.DataAcces.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCFirstApp.DataAcces.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCFirstApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "SuperSport"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Hypersport"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Combi"
                        });
                });

            modelBuilder.Entity("MVCFirstApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KilometresDriven")
                        .HasColumnType("int");

                    b.Property<int>("PowerInKilowatts")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("YearOfConstruction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            CarModel = "M3",
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 106524,
                            PowerInKilowatts = 136,
                            Price = 25000.0,
                            YearOfConstruction = 2014
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes",
                            CarModel = "M3",
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 196524,
                            PowerInKilowatts = 128,
                            Price = 38000.0,
                            YearOfConstruction = 2016
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Seat",
                            CarModel = "M3",
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 326524,
                            PowerInKilowatts = 77,
                            Price = 7500.0,
                            YearOfConstruction = 2013
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Skoda",
                            CarModel = "M3",
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 126524,
                            PowerInKilowatts = 84,
                            Price = 3600.0,
                            YearOfConstruction = 2012
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Suzuki",
                            CarModel = "M3",
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 136524,
                            PowerInKilowatts = 55,
                            Price = 500.0,
                            YearOfConstruction = 2004
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Citroen",
                            CarModel = "M3",
                            CategoryId = 3,
                            Description = "",
                            ImageUrl = "",
                            KilometresDriven = 116524,
                            PowerInKilowatts = 103,
                            Price = 2999.0,
                            YearOfConstruction = 2010
                        });
                });

            modelBuilder.Entity("MVCFirstApp.Models.Product", b =>
                {
                    b.HasOne("MVCFirstApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
